#############################################################################
# Generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#  Jul 18, 2022 10:05:58 AM CEST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x205+420+350
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1425 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "pyinstaller Gui"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    checkbutton $top.che47 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text onefile -variable che47 
    vTcl:DefineAlias "$top.che47" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che51 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -overrelief groove -text oneDire -variable che51 
    vTcl:DefineAlias "$top.che51" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {sel file} 
    vTcl:DefineAlias "$top.but52" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text start 
    vTcl:DefineAlias "$top.but53" "Button2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che55 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -command {Rando name folder} -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text RandomNameFolder -variable che55 
    vTcl:DefineAlias "$top.che55" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font "-family Ani -size 14 -weight bold -slant italic -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -text {convert Setup} 
    vTcl:DefineAlias "$top.lab58" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 10 
    vTcl:DefineAlias "$top.ent59" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -foreground $vTcl(actual_gui_fg) -text {save name folder:} 
    vTcl:DefineAlias "$top.lab60" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but61 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Ok 
    vTcl:DefineAlias "$top.but61" "Button3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.che47 \
        -in $top -x 0 -relx 0.217 -y 0 -rely 0.341 -width 0 -relwidth 0.178 \
        -height 0 -relheight 0.102 -anchor nw -bordermode ignore 
    place $top.che51 \
        -in $top -x 0 -relx 0.217 -y 0 -rely 0.244 -width 0 -relwidth 0.178 \
        -height 0 -relheight 0.098 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.233 -y 0 -rely 0.634 -width 73 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.683 -width 73 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che55 \
        -in $top -x 0 -relx 0.6 -y 0 -rely 0.244 -width 0 -relwidth 0.295 \
        -height 0 -relheight 0.112 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.049 -width 0 -relwidth 0.248 \
        -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.439 -width 86 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.341 -width 0 -relwidth 0.232 \
        -height 0 -relheight 0.102 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.767 -y 0 -rely 0.439 -width 33 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

